version: "3.7"

services:

  plugin:
    image: dockware/dev:6.4.8.1
    container_name: plugin
    ports:
      - "1000:80"
      - "3306:3306"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "./shop/src:/var/www/html"
      # excludes ---------------------------
      - '/var/www/html/vendor'
      - '/var/www/html/var/cache'
      - '/var/www/html/public/bundles'
      - '/var/www/html/public/media'
      - '/var/www/html/public/theme'
      - '/var/www/html/public/thumbnail'

  shop:
    image: dockware/essentials:latest
    container_name: shop
    ports:
      - "80:80"
      - "22:22"
      - "3306:3306"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "./shop/src:/var/www/html"
      # excludes ---------------------------
      - '/var/www/html/vendor'
      - '/var/www/html/var/cache'
      - '/var/www/html/public/bundles'
      - '/var/www/html/public/media'
      - '/var/www/html/public/theme'
      - '/var/www/html/public/thumbnail'

volumes:
  db_volume:
    driver: local
